### Tensorflow - Fundamentals

#### In this notebook, we 're going to cover some of the most fundamental concepts of tensors using Tensorflow

* Introduction to tensors
* Getting information from tensors
* Manipulating tensors
* Tensors & Numpy
* Using @tf.function (a way to speed up your regular Python functions)
* Using GPUs with TensorFlow (or TPUs)
* Exercises

#### Introduction to Tensors

* Scalar: A single number
* Vector: A number with direction (e.g. wind speed and direction)
* Matrix: A 2-dimensional array of number
* Tensor: A n-dimensional array of numbers (when n can be any number, a 0-dimensional tensor is a scalar, a 1-dimensional tensor is a vector)

##### Creating tensors with `tf.constant`:

In [1]:
# Import Tensorflow
import tensorflow as tf
print(tf.__version__)

2.17.0


In [2]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# Check the number of dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [4]:
# Create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>

In [5]:
# Check the dimension of our vecto
vector.ndim

1

In [6]:
# Create a matrix (has more than 1 dimension)

matrix = tf.constant([[10, 7],[7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]])>

In [7]:
matrix.ndim

2

In [8]:
# Create a matrix (has more than 1 dimension)

another_matrix = tf.constant([[10., 7.],[7., 10.], [9., 8.]], dtype=tf.float16) # Specify the data type 
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 7., 10.],
       [ 9.,  8.]], dtype=float16)>

In [9]:
another_matrix.ndim

2

In [10]:
tensor = tf.constant([[[1, 2, 3], 
                             [4, 5, 6], 
                             [7, 8, 9]],

                            [[10, 11, 12], 
                             [13, 14, 15], 
                             [16, 17, 18]],

                            [[19, 20, 21], 
                             [22, 23, 24], 
                             [25, 26, 27]]])
tensor

<tf.Tensor: shape=(3, 3, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])>

In [11]:
tensor.ndim

3

##### Creating tensors with `tf.Variable`:

In [12]:
changeable_tensor = tf.Variable([10,10])
unchangeable_tensor = tf.constant([10,10])

changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10, 10])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>)

In [13]:
# Let's try change one of the elements in our changeable tensor

# changeable_tensor[0] = 7 no funcionaría
# unchangeable_tensor[0].assign(7) tampoco funcionaría

changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([ 7, 10])>

##### Creating random tensors with `tf.random.Generator`:

Suelen utilizarse para inicializar los pesos al principio

In [14]:
# Podemos utilizar distintas distribuciones normal, ....

random_1 = tf.random.Generator.from_seed(43)
random_1 = random_1.normal(shape=(1,2))

random_2 = tf.random.Generator.from_seed(43)
random_2 = random_2.normal(shape=(1,2))

random_1, random_2, random_1 == random_2


(<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(1, 2), dtype=bool, numpy=array([[ True,  True]])>)

##### Shuffle a tensor (Valuable to shuffle the data and prevent a wrong training) `tf.random.Generator`:

In [15]:
# Shuffle a tensor
not_shuffled = tf.constant([[10., 7.],[7., 10.], [9., 8.]]) 
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[10.,  7.],
       [ 7., 10.],
       [ 9.,  8.]], dtype=float32)>

In [16]:
# Shuffle our non-shuffled tensor
shuffled = tf.random.shuffle(not_shuffled, seed=42)
shuffled

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 9.,  8.],
       [ 7., 10.],
       [10.,  7.]], dtype=float32)>

In [17]:
# Random seed generator in tf

tf.random.set_seed(42) # Global level random seed
tf.random.shuffle(not_shuffled, seed=42) # Operation level random seed

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[10.,  7.],
       [ 7., 10.],
       [ 9.,  8.]], dtype=float32)>

##### Other ways to create tensors

In [18]:
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [19]:
tf.zeros((10,7))

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

##### Turn Numpy arrays into tensors

The main difference between NumPy arrays and Tensorflow tensors is that tensors can be run on a GPU (much faster for numerical computing)

In [20]:
import numpy as np

# Numpy array de 1 a n
numpy_A = np.arange(1, 25, dtype=np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [21]:
A = tf.constant(numpy_A)

# El shape dice x matrices, con y filas y z columnas
B = tf.constant(numpy_A, shape=(2, 3, 4))

A, B

(<tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24])>,
 <tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]])>)

##### Tensor attributes

When dealing with tensor you probably want to be aware of the following attributes

* Shape: The shape of a tensor describes the number of elements along each dimension of the tensor. It is represented as a tuple of integers.
* Rank: The rank of a tensor is the number of dimensions or axes it has. For example, a scalar has rank 0, a vector has rank 1, a matrix has rank 2, and so on.
* Axis or dimension: An axis (or dimension) is a specific dimension of a tensor. It is indexed from 0. For example, in a 2D tensor (matrix), axis 0 refers to the rows, and axis 1 refers to the columns.
* Size: The size of a tensor is the total number of elements in the tensor. It is the product of all the dimensions' sizes.

In [22]:
rank_4_tensor = tf.zeros(shape=[2,3,4,5])
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [23]:
2 * 3 * 4 * 5

120

In [24]:
# Get various attributes of our tensor
print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimensions (rank):", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along the 0 axis:", rank_4_tensor.shape[0])
print("Elements along the last axis:", rank_4_tensor.shape[-1])
print("Total number of elements in our tensor:", tf.size(rank_4_tensor))
print("Total number of elements in our tensor:", tf.size(rank_4_tensor).numpy())

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along the 0 axis: 2
Elements along the last axis: 5
Total number of elements in our tensor: tf.Tensor(120, shape=(), dtype=int32)
Total number of elements in our tensor: 120


##### Indexing tensors

Tensors can be indexed just like Python lists.

In [25]:
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [26]:
# Get the first element from each dimension from each index except for the final one 

rank_4_tensor[:1, :1, 1:, :]

<tf.Tensor: shape=(1, 1, 3, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [27]:
# Get the last item of each of row of our rank 2 tensor

rank_2_tensor = tf.constant([[2,7],[7,2]])

rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 2])>

In [28]:
# Add in extra dimension at the end 
# Los puntos deja al resto de accesos anteriores a : tipo -> rank_2_tensor[:,:,tf.newaxis]
rank_3_tensor = rank_2_tensor[..., tf.newaxis]

rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[2],
        [7]],

       [[7],
        [2]]])>

In [29]:
# Alternative to tf.newaxis

tf.expand_dims(rank_2_tensor, axis=-1) # El -1 significa el último axis
tf.expand_dims(rank_2_tensor, axis=0) # Expande el primer axis

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[2, 7],
        [7, 2]]])>

##### Manipulating tensors (Tensor operations)

**Basic operations**



In [30]:
# Suma n a todos los valores

# Funcionará con cualquier operador: + - * /
tensor = tf.constant([[2,7],[7,2]])
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 70],
       [70, 20]])>

In [31]:
# We cna use the tensor built-in function too

tf.multiply(tensor, 10)
tf.add(tensor, 5)
tf.divide(tensor, 5)
tf.subtract(tensor, 5)

# Para aplicar funciones usamos map_fn
def myFunction(x):
    return x + 2

tf.map_fn(myFunction, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[4, 9],
       [9, 4]])>



**Matrix multiplication**

Usamos `tf.matmul`

Para ello debemos tener en cuenta:

- Regla de compatibilidad: El número de columnas de la primera matriz debe ser igual al número de filas de la segunda.

- Dimensiones de la matriz resultante: La matriz resultante tiene tantas filas como la primera matriz y tantas columnas como la segunda.

- Cálculo de los elementos: Cada elemento de la matriz resultante es el producto punto entre una fila de la primera matriz y una columna de la segunda.

In [37]:
# Haciendolo con matmul de tf
tf.matmul(tensor,tensor)

# Haciendolo con Python operator "@"
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[53, 28],
       [28, 53]])>

In [44]:
# Create a tensor (3,2) tensor
X = tf.constant([[1, 2], [3, 4], [5, 6]])

# Create another (3,2) tensor 
Y = tf.constant([[7, 8], [9, 10], [11, 12]])


# X@Y - No se pueden multiplicar xque no cumple las propiedades de las matrices,
# por lo que podemos hacer reshape o transmute

# Cambiando el shape de la matriz 
tf.reshape(Y, shape=(2,3)) @ X
tf.matmul(tf.reshape(Y, shape=(2,3)), X)

# Usando la matriz traspuesta
tf.transpose(Y), tf.reshape(Y,shape=(2,3))

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[ 7,  9, 11],
        [ 8, 10, 12]])>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[ 7,  8,  9],
        [10, 11, 12]])>)

**The dot product**

Matrix multiplication is also referred as the dot product.

You can perform matrix multiplication using:

* `tf.matmul()`
* `tf.tensordot()`
* `@`

In [49]:
#Perform the dot product on X and Y (requieres X or Y to be transposed)

# Todo esto nos daría resultados distintos

A = tf.tensordot(tf.transpose(X), Y, axes=1)
B = tf.tensordot(X, tf.transpose(Y), axes=1)
C = tf.tensordot(X, tf.reshape(Y, shape=(2,3)), axes=1)

print(A, B, C)

tf.Tensor(
[[ 89  98]
 [116 128]], shape=(2, 2), dtype=int32) tf.Tensor(
[[ 23  29  35]
 [ 53  67  81]
 [ 83 105 127]], shape=(3, 3), dtype=int32) tf.Tensor(
[[ 27  30  33]
 [ 61  68  75]
 [ 95 106 117]], shape=(3, 3), dtype=int32)


**Changing the datatype of a tensor**

Esto puede llegar a reducir el tiempo de ejecución a costa de un poco de precisión

In [56]:
B = tf.constant([1.7, 7.4])

C = tf.constant([1, 7])

D = tf.cast(B, dtype=tf.float16)

E = tf.cast(C, dtype=tf.float32)

B.dtype, C.dtype, D.dtype, E.dtype

(tf.float32, tf.int32, tf.float16, tf.float32)

**Aggregating tensors**

Aggregating tensors = condensing then from multiple values down to a smaller ammount of values

* Get the minimun
* Get the maximun
* Get the mean of a tensor
* Get the sum of a tensor

In [58]:
# Get the absolute values

F = tf.constant([-2,-7])
tf.abs(F)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 7])>

In [59]:
# Create a random tensor with values between 0 and 100 of size 50

E = tf.constant(np.random.randint(0, 100, size=50))
E

<tf.Tensor: shape=(50,), dtype=int32, numpy=
array([96, 10, 26, 89, 73, 99, 45, 86, 10, 30, 65, 76, 51,  7,  9, 41, 81,
       19, 70,  7, 55, 30, 98, 20, 90, 78,  9, 85, 31, 29,  2, 49, 12, 75,
       10, 78, 87, 95, 18, 36, 33, 15, 71, 91,  5, 70, 96, 73,  5, 37])>

In [87]:
tf.reduce_min(E), 
tf.reduce_max(E), 
tf.reduce_mean(E), 
tf.reduce_sum(E), 
tf.math.reduce_std(tf.cast(E, tf.float32)),  
tf.math.reduce_variance(tf.cast(E, tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=1054.5283>

**Find the positional maximun and minimun**

In [96]:
# Creating a new tensor for finding positional minimun and maximun
tf.random.set_seed(42)

F = tf.random.uniform(shape=[50])

# Find the positional maximun
tf.argmax(F)

# Index on our largest values position
F[tf.argmax(F)]

# Find max value of F
tf.reduce_max(F)

# Check for equality
F[tf.argmax(F)] == tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [99]:
# Find the positional minimun
tf.argmin(F)

# Find the minimun using the positional minimun index
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

**Squeezing a tensor (removing all single dimensions)**

Remove dimensions of size 1 from the shape of a tensor

In [104]:
G = tf.constant(tf.random.uniform(shape=[50]), shape=(1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.7413678 , 0.62854624, 0.01738465, 0.3431449 , 0.51063764,
           0.3777541 , 0.07321596, 0.02137029, 0.2871771 , 0.4710616 ,
           0.6936141 , 0.07321334, 0.93251204, 0.20843053, 0.70105827,
           0.45856392, 0.8596262 , 0.92934334, 0.20291913, 0.76865506,
           0.60016024, 0.27039742, 0.88180614, 0.05365038, 0.42274463,
           0.89037776, 0.7887033 , 0.10165584, 0.19408834, 0.27896714,
           0.39512634, 0.12235212, 0.38412368, 0.9455296 , 0.77594674,
           0.94442344, 0.04296565, 0.4746096 , 0.6548251 , 0.5657116 ,
           0.13858628, 0.3004663 , 0.3311677 , 0.12907016, 0.6435652 ,
           0.45473957, 0.68881893, 0.30203617, 0.49152803, 0.26529062]]]]],
      dtype=float32)>

In [105]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [107]:
G_squeezed = tf.squeeze(G)
G_squeezed

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.7413678 , 0.62854624, 0.01738465, 0.3431449 , 0.51063764,
       0.3777541 , 0.07321596, 0.02137029, 0.2871771 , 0.4710616 ,
       0.6936141 , 0.07321334, 0.93251204, 0.20843053, 0.70105827,
       0.45856392, 0.8596262 , 0.92934334, 0.20291913, 0.76865506,
       0.60016024, 0.27039742, 0.88180614, 0.05365038, 0.42274463,
       0.89037776, 0.7887033 , 0.10165584, 0.19408834, 0.27896714,
       0.39512634, 0.12235212, 0.38412368, 0.9455296 , 0.77594674,
       0.94442344, 0.04296565, 0.4746096 , 0.6548251 , 0.5657116 ,
       0.13858628, 0.3004663 , 0.3311677 , 0.12907016, 0.6435652 ,
       0.45473957, 0.68881893, 0.30203617, 0.49152803, 0.26529062],
      dtype=float32)>

**One-hot encoding tensors**

Un One Hot Encoder es una técnica de preprocesamiento utilizada en machine learning para convertir datos categóricos en una representación numérica que pueda ser utilizada por modelos de aprendizaje automático. La idea principal es transformar cada categoría en un vector binario donde solo un valor es 1 y los demás son 0.

In [119]:
some_list = [0, 1, 2, 3]

# ONE HOT ENCODE OUR LIST OF INDICES
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [116]:
# Specify custom values for one hot encoding
tf.one_hot(some_list, depth=4, on_value="VALOR-TRUE", off_value="VALOR-FALSE")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'VALOR-TRUE', b'VALOR-FALSE', b'VALOR-FALSE', b'VALOR-FALSE'],
       [b'VALOR-FALSE', b'VALOR-TRUE', b'VALOR-FALSE', b'VALOR-FALSE'],
       [b'VALOR-FALSE', b'VALOR-FALSE', b'VALOR-TRUE', b'VALOR-FALSE'],
       [b'VALOR-FALSE', b'VALOR-FALSE', b'VALOR-FALSE', b'VALOR-TRUE']],
      dtype=object)>

**Squaring, log, square root**

In [126]:
H = tf.range(1, 10)

In [125]:
tf.square(H)
tf.sqrt(tf.cast(H, dtype=tf.float32))
tf.math.log(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

**Tensors and Numpy**

Tensorflow intereacts beautifully with Numpy Arrays

In [127]:
# Create a tensor directly from a Numpy array
J = tf.constant(np.array([3.,7.,10.]))

In [128]:
# Convert our tensor back to a Numpy array
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [129]:
# Convert tensor J to a Numpy array
J.numpy(), type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [130]:
J = tf.constant([3.])
J.numpy()[0]

3.0

# The default types of each types are slightly different
numpy_J = tf.constant(np.array([3.,7.,10.]))
tensor_J = tf.constant([3.,7., 10.])

#Check the datatypes of each
numpy_J.dtype, tensor_J.dtype

**Finding access to GPUs**

In [135]:
tf.config.list_physical_devices()

# Lo suyo sería correr tensorflow en GPU y no en CPU


[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

In [136]:
!nvidia-smi

Sun Aug 18 17:57:00 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 556.24                 Driver Version: 556.24         CUDA Version: 12.5     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4060 ...  WDDM  |   00000000:01:00.0 Off |                  N/A |
| N/A   36C    P3             13W /   45W |       0MiB /   8188MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

**Ejercicios**

1-Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().

2-Find the shape, rank and size of the tensors you created in 1.

3-Create two tensors containing random values between 0 and 1 with shape [5, 300].

4-Multiply the two tensors you created in 3 using matrix multiplication.
    
5-Multiply the two tensors you created in 3 using dot product.
    
6-Create a tensor with random values between 0 and 1 with shape [224, 224, 3].
    
7-Find the min and max values of the tensor you created in 6 along the first axis.
    
8-Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].
    
9-Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.

10-One-hot encode the tensor you created in 9.